### ISSUE TITLE
Website DNS/ Domain broken

### ISSUE THREAD

**Issue by LivingWithHippos** [ManuelGil/Reset-Windows-Update-Tool#12]
To make links work I need to remove the www and https every time. Tried on my computer and on a firend's one (different dns and browser and ip).
Broken:
- https://www.wureset.com/
- www.wureset.com/

Working (copy and paste this in the address bar):
- wureset.com

Even the download page on the site itself is not working
Broken:
- https://wureset.com/downloads.php

Working:
- wureset.com/downloads.php

EDIT:
Insecure links work. You probably just have a problem with your certificate, http://wureset.com/downloads.php is ok

Just saw #9 , your certificate probably expires every march ;D have a good day

**Comment by sbergene** [comment]
? help is pointing to unresolvable url http://docs.wureset.com/.
Nice tool, by the way :-)

**Comment by ManuelGil** [comment]
@LivingWithHippos @sbergene, so sorry for the issue. Due to the economic fluctuation in my region, server costs have taken me on a long journey in search of a better option.

I'm still in migration processes and I hope I can find the right option to solve everyone's needs.

You have a great day :smile:

**Comment by borekon** [comment]
> 
> 
> @LivingWithHippos @sbergene, so sorry for the issue. Due to the economic fluctuation in my region, server costs have taken me on a long journey in search of a better option.
> 
> I'm still in migration processes and I hope I can find the right option to solve everyone's needs.

Let me know if i can help you with that

**Comment by ManuelGil** [comment]
Thanks to all of you, due to cost overruns in the hosting of [https://www.wureset.com/](https://www.wureset.com/), a migration was made to a new service which has shown good performance so far.

Also, a change has been made to [https://www.wureset.com/](https://www.wureset.com/) to make its loading faster and better usability.

Donations made to the project ensure that we keep this service active for much longer.
