### ISSUE TITLE
(SOLVED) renaming "%SYSTEMROOT%\SoftwareDistribution" failed due to permision

### ISSUE THREAD

**Issue by cramaboule** [ManuelGil/Reset-Windows-Update-Tool#33]
**Describe the bug**
On some PC:
ren "%SYSTEMROOT%\SoftwareDistribution" SoftwareDistribution.bak

cannot be done because of permission issue and program stops (even eleveted)

**Expected behavior**
Either fix permision either copy the content into a new folder and delete content
Program should continue anyway

-   OS: Win10 Family

**Comment by ManuelGil** [comment]
Hi @cramaboule ,

I recommend you read this [wiki](https://github.com/ManuelGil/Reset-Windows-Update-Tool/wiki/Reset-Components#the-windows-update-service-could-not-be-stopped) first. Please confirm if this information solves your problem or if otherwise it is necessary to look for another alternative.

**Comment by cramaboule** [comment]
Hi @ManuelGil ,

Thanks, permison was going well under windows recovery mode!

But still, Windows update are not working: WU says: they are some GPO and the PC is NOT in a domain, it is on 'workgroup' !!! Any ideas ???
