### ISSUE TITLE
ssl certificate expired

### ISSUE THREAD

**Issue by Djfe** [ManuelGil/Reset-Windows-Update-Tool#9]
If I open help from the application, then it opens the https version of wureset.com
But the ssl certificate expired in march.

**Comment by ManuelGil** [comment]
Hi @Djfe,

Since the application's help page does not require logins or personal data management, it is not necessary to update the certificate.

The next update of this tool already has an updated [link](https://github.com/ManuelGil/Reset-Windows-Update-Tool/blob/master/wureset/lang/english.txt#L154) without the https.

**Comment by Djfe** [comment]
cool, thx for the fix!
I kind of disagree with your statement, so I'll leave this here:
https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https
(intruders can exchange the file you are offering for users on-the-fly and insert malware)

But it's totally up-to-you whether you want to change this :)

**Comment by Djfe** [comment]
a bit shorter and clearer:
https://https.cio.gov/everything/

**Comment by ManuelGil** [comment]
The domain [wureset.com](https://wureset.com) has been updated with a new ssl certificate.

Thank you.
